# Titanic Model Implementation

In [2]:
#import all libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = sns.load_dataset("titanic")

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [7]:
# drop the column not impact the value
df.drop(["deck", "embark_town", "alive", "class", "who", "adult_male"], axis=1, inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [9]:
df["age"].fillna(df["age"].mean(), inplace=True)

In [10]:
df.dropna(subset=["embarked"], inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [13]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [14]:
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [15]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [ ]:
df = df.astype(int)

In [16]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [17]:
x= df.drop("survived",axis=1)
y = df["survived"]

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42)

In [ ]:
#Logistic Regression model ready
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [21]:
y_pred = model.predict(x_test)

In [22]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1])

In [23]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
425    0
102    0
200    0
399    1
669    1
Name: survived, Length: 223, dtype: int64

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [25]:
accuracy_score(y_test,y_pred)

0.8071748878923767

In [26]:
confusion_matrix(y_test,y_pred)

array([[118,  23],
       [ 20,  62]])

In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.84      0.85       141
           1       0.73      0.76      0.74        82

    accuracy                           0.81       223
   macro avg       0.79      0.80      0.79       223
weighted avg       0.81      0.81      0.81       223

In [28]:
df

     survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  22.000000      1      0   7.2500         2  False
1           1       1    0  38.000000      1      0  71.2833         0  False
2           1       3    0  26.000000      0      0   7.9250         2   True
3           1       1    0  35.000000      1      0  53.1000         2  False
4           0       3    1  35.000000      0      0   8.0500         2   True
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  27.000000      0      0  13.0000         2   True
887         1       1    0  19.000000      0      0  30.0000         2   True
888         0       3    0  29.699118      1      2  23.4500         2  False
889         1       1    1  26.000000      0      0  30.0000         0   True
890         0       3    1  32.000000      0      0   7.7500         1   True

[889 rows x 9 columns]

In [29]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [30]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

# kneighbors model apply

In [ ]:
#scalled the data before apply the model

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
knn_model = KNeighborsClassifier(n_neighbors= 5)
knn_model.fit(x_train_scaled,y_train)

KNeighborsClassifier()

In [33]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [34]:
accuracy_score(y_test,y_pred_knn)

0.7847533632286996

In [35]:
confusion_matrix(y_test,y_pred_knn)

array([[115,  26],
       [ 22,  60]])

In [36]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.84      0.82      0.83       141
           1       0.70      0.73      0.71        82

    accuracy                           0.78       223
   macro avg       0.77      0.77      0.77       223
weighted avg       0.79      0.78      0.79       223

# Navie Bayes

In [37]:
from sklearn.naive_bayes import GaussianNB

In [38]:
model_NB = GaussianNB()

In [39]:
model_NB.fit(x_train,y_train)

GaussianNB()

In [40]:
y_pred_NB = model_NB.predict(x_test)

In [41]:
accuracy_score(y_test,y_pred_NB)

0.7802690582959642

In [42]:
confusion_matrix(y_test,y_pred_NB)

array([[112,  29],
       [ 20,  62]])

In [43]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82       141
           1       0.68      0.76      0.72        82

    accuracy                           0.78       223
   macro avg       0.76      0.78      0.77       223
weighted avg       0.79      0.78      0.78       223

# Descion Tree Calssifier

In [44]:
from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier(random_state=42)

In [45]:
model_DT.fit(x_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [46]:
y_pred_DT = model_DT.predict(x_test_scaled)

In [47]:
y_pred_DT

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1])

In [48]:
accuracy_score(y_test,y_pred_DT)

0.757847533632287

In [49]:
confusion_matrix(y_test,y_pred_DT)

array([[115,  26],
       [ 28,  54]])

In [50]:
print(classification_report(y_test,y_pred_DT))

              precision    recall  f1-score   support

           0       0.80      0.82      0.81       141
           1       0.68      0.66      0.67        82

    accuracy                           0.76       223
   macro avg       0.74      0.74      0.74       223
weighted avg       0.76      0.76      0.76       223

# Support Vector svm

In [51]:
from sklearn.svm import SVC

In [52]:
model_svm = SVC(kernel = 'linear')

In [54]:
model_svm.fit(x_train_scaled, y_train)

SVC(kernel='linear')

In [55]:
y_pred_svc = model_svm.predict(x_test_scaled)

In [56]:
accuracy_score(y_test,y_pred_svc)

0.8026905829596412

In [57]:
confusion_matrix(y_test,y_pred_svc)

array([[119,  22],
       [ 22,  60]])

In [58]:
print(classification_report(y_test,y_pred_svc))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84       141
           1       0.73      0.73      0.73        82

    accuracy                           0.80       223
   macro avg       0.79      0.79      0.79       223
weighted avg       0.80      0.80      0.80       223

In [59]:
df

     survived  pclass  sex        age  sibsp  parch     fare  embarked  alone
0           0       3    1  22.000000      1      0   7.2500         2  False
1           1       1    0  38.000000      1      0  71.2833         0  False
2           1       3    0  26.000000      0      0   7.9250         2   True
3           1       1    0  35.000000      1      0  53.1000         2  False
4           0       3    1  35.000000      0      0   8.0500         2   True
..        ...     ...  ...        ...    ...    ...      ...       ...    ...
886         0       2    1  27.000000      0      0  13.0000         2   True
887         1       1    0  19.000000      0      0  30.0000         2   True
888         0       3    0  29.699118      1      2  23.4500         2  False
889         1       1    1  26.000000      0      0  30.0000         0   True
890         0       3    1  32.000000      0      0   7.7500         1   True

[889 rows x 9 columns]

In [60]:
X = df.drop('survived',axis = 1)
y = df['survived']

In [61]:
from sklearn.model_selection import cross_val_score

In [62]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [63]:
scores = cross_val_score(model_svm,X_scaled,y,cv = 5,scoring= 'accuracy')

In [64]:
print(scores)

[0.79775281 0.80898876 0.78651685 0.75280899 0.78531073]

In [65]:
print(scores.mean())

0.7862756300387227